---
# This playbook install the common packages
- hosts: all
  become: true

  tasks:
    - name: Install OpenJDK
      apt:
        name: openjdk-16-jdk
        state: present

    - name: Install OpenJDK JRE
      apt:
        name: openjdk-16-jre-headless
        state: present
