# D2 Settings
direction: right

# Title
title: VSCode hosted on OCI with CloudFlare Access (Zero Trust) {
  near: top-center
  shape: text
  style: {
    font-size: 29
    bold: true
    underline: true
  }
}

# OCI Infrastructure
VCN: {
  Subnet: {
    Instance: {
      Root Volume: {
        cloudflared
      }
    }
    Persitent Volume: Persistent Volume (/data)
    Instance -> Persistent Volume
  }
  Internet Gateway <- _.VCN.Subnet.Instance.Root Volume.cloudflared: Tunnel
}

# Internet
Internet.shape: cloud

# CloudFlare Infrastructure
CloudFlare: {
  Access: Access (Zero Trust)
  _.VCN.Internet Gateway -> _.Internet -> _.CloudFlare.Access
}

# User
User: {
  shape: person
}
Browser: {
  shape: page
  _.User -> _.Browser
}
CloudFlare WARP: {
  label: CloudFlare WARP (client)
  _.Browser -> _.CloudFlare WARP -> _.Internet
}
