# D2 Settings
direction: right

# Title
title: VSCode Server hosted on OCI with Zero Trust Network (CloudFlare Access) {
  near: top-center
  shape: text
  style: {
    font-size: 29
    bold: true
    underline: true
  }
}

# OCI Infrastructure
VCN: {
  Subnet: {
    Instance: {
      Root Volume: {
        VSCode Server {
          shape: image
          icon: ./icons/vscode.svg
        }
        cloudflared: {
          shape: image
          icon: ./icons/cloudflare.svg
        }
        VSCode Server <-> cloudflared
      }
    }
    Persistent Volume: {
      label: Persistent Volume (/data)
      Tools: {
        docker: {
          shape: image
          icon: ./icons/docker.svg
          width: 50
          height: 50
        }
        terraform: {
          shape: image
          icon: ./icons/terraform.svg
          width: 50
          height: 50
        }
      }
      Config: {
        shape: page
      }
    }
    Instance -> Persistent Volume
  }
  Internet Gateway <-> _.VCN.Subnet.Instance.Root Volume.cloudflared: Tunnel
}

# CloudFlare Infrastructure
CloudFlare Access: {
  shape: image
  icon: ./icons/cloudflare.svg
  _.VCN.Internet Gateway <-> _.CloudFlare Access
}

# User
User: {
  shape: person
}
Browser: {
  shape: page
  _.User -> _.Browser
}
CloudFlare WARP: {
  label: CloudFlare WARP (client)
  shape: image
  icon: ./icons/cloudflare.svg
  _.Browser -> _.CloudFlare WARP -> _.CloudFlare Access
}
