---
# This playbook install the Cloudflare Agent (cloudflared)
- hosts: server
  become: true

  tasks:
    - name: Download Cloudflare Agent (deb)
      get_url:
        url: "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64.deb"
        dest: "/tmp/cloudflared-linux-arm64.deb"

    - name: Install Cloudflare Agent
      apt:
        deb: "/tmp/cloudflared-linux-arm64.deb"
