---
# This playbook install the common packages
- hosts: server
  become: true
  gather_facts: false

  tasks:
    - name: Install common packages (unzip, openjdk)
      apt:
        pkg:
          - unzip
          - openjdk-16-jdk
          - openjdk-16-jre-headless
