---
# This playbook install the common packages
- hosts: server
  become: true
  gather_facts: false

  tasks:
    - name: Install common packages (unzip, pip, openjdk)
      apt:
        pkg:
          - unzip
          - python3-pip
          - openjdk-16-jdk
          - openjdk-16-jre-headless

    - name: Install Ansible & pre-commit
      pip:
        name:
          - ansible
          - pre-commit
